
void push(node in)
node pop() 
node copyStackHelper(node curNode)
stack copyStack(stack origStack)
void freeList(node in)
void freeNode(node in)
void freeStack(stack in)
bool quotationEquals(node a, node b)
bool nodeEquals(node a, node b)
void append(node appendee, node quotation)
